[INFO     2010-08-31 13:53:04,303 bulkloader.py] Logging to bulkloader-log-20100831.135304
[INFO     2010-08-31 13:53:04,303 bulkloader.py] Throttling transfers:
[INFO     2010-08-31 13:53:04,303 bulkloader.py] Bandwidth: 250000 bytes/second
[INFO     2010-08-31 13:53:04,303 bulkloader.py] HTTP connections: 8/second
[INFO     2010-08-31 13:53:04,303 bulkloader.py] Entities inserted/fetched/modified: 20/second
[INFO     2010-08-31 13:53:04,303 bulkloader.py] Batch Size: 10
[INFO     2010-08-31 13:53:04,305 bulkloader.py] Opening database: bulkloader-progress-20100831.135304.sql3
[DEBUG    2010-08-31 13:53:04,321 adaptive_thread_pool.py] [Thread-1] WorkerThread: started
[DEBUG    2010-08-31 13:53:04,331 adaptive_thread_pool.py] [Thread-2] WorkerThread: started
[DEBUG    2010-08-31 13:53:04,342 adaptive_thread_pool.py] [Thread-3] WorkerThread: started
[DEBUG    2010-08-31 13:53:04,352 adaptive_thread_pool.py] [Thread-4] WorkerThread: started
[DEBUG    2010-08-31 13:53:04,362 adaptive_thread_pool.py] [Thread-5] WorkerThread: started
[DEBUG    2010-08-31 13:53:04,373 adaptive_thread_pool.py] [Thread-6] WorkerThread: started
[DEBUG    2010-08-31 13:53:04,383 adaptive_thread_pool.py] [Thread-7] WorkerThread: started
[DEBUG    2010-08-31 13:53:04,393 adaptive_thread_pool.py] [Thread-8] WorkerThread: started
[DEBUG    2010-08-31 13:53:04,404 adaptive_thread_pool.py] [Thread-9] WorkerThread: started
[DEBUG    2010-08-31 13:53:04,414 adaptive_thread_pool.py] [Thread-10] WorkerThread: started
[DEBUG    2010-08-31 13:53:04,425 bulkloader.py] Configuring remote_api. url_path = /remote_api, servername = mk10koers.appspot.com
[DEBUG    2010-08-31 13:53:04,703 bulkloader.py] Bulkloader using app_id: mk10koers
[INFO     2010-08-31 13:53:04,703 bulkloader.py] Connecting to mk10koers.appspot.com/remote_api
[DEBUG    2010-08-31 13:53:05,330 bulkloader.py] [Thread-11] ProgressTrackerThread: started
[DEBUG    2010-08-31 13:53:05,340 bulkloader.py] [Thread-12] DataSourceThread: started
[INFO     2010-08-31 13:53:05,340 bulkloader.py] Starting import; maximum 10 entities per post
[DEBUG    2010-08-31 13:53:05,352 adaptive_thread_pool.py] [Thread-1] Got work item [1-10]
[DEBUG    2010-08-31 13:53:05,362 bulkloader.py] [Thread-12] DataSourceThread: exiting
[DEBUG    2010-08-31 13:53:05,370 bulkloader.py] Waiting for worker threads to finish...
[ERROR    2010-08-31 13:53:05,372 adaptive_thread_pool.py] [Thread-1] WorkerThread:
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/adaptive_thread_pool.py", line 150, in WorkOnItems
    status, instruction = item.PerformWork(self.__thread_pool)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 846, in _TransferItem
    self.content = self.request_manager.EncodeContent(self.rows)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 1267, in EncodeContent
    entity = loader.create_entity(values, key_name=key, parent=parent)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 2522, in create_entity
    properties[name] = converter(val)
ValueError: invalid literal for int() with base 10: 'Gewicht'
[DEBUG    2010-08-31 13:53:05,375 adaptive_thread_pool.py] [Thread-1] WorkerThread: exiting
[INFO     2010-08-31 13:53:05,375 adaptive_thread_pool.py] [Thread-3] Backing off due to errors: 1.0 seconds
[INFO     2010-08-31 13:53:05,881 bulkloader.py] An error occurred. Shutting down...
[DEBUG    2010-08-31 13:53:05,882 adaptive_thread_pool.py] [Thread-5] WorkerThread: exiting
[DEBUG    2010-08-31 13:53:05,883 adaptive_thread_pool.py] [Thread-6] WorkerThread: exiting
[DEBUG    2010-08-31 13:53:05,884 adaptive_thread_pool.py] [Thread-7] WorkerThread: exiting
[DEBUG    2010-08-31 13:53:05,884 adaptive_thread_pool.py] [Thread-4] WorkerThread: exiting
[DEBUG    2010-08-31 13:53:05,884 adaptive_thread_pool.py] [Thread-10] WorkerThread: exiting
[DEBUG    2010-08-31 13:53:05,884 adaptive_thread_pool.py] [Thread-9] WorkerThread: exiting
[DEBUG    2010-08-31 13:53:05,885 adaptive_thread_pool.py] [Thread-8] WorkerThread: exiting
[DEBUG    2010-08-31 13:53:05,885 adaptive_thread_pool.py] [Thread-2] WorkerThread: exiting
[DEBUG    2010-08-31 13:53:05,886 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2010-08-31 13:53:05,886 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2010-08-31 13:53:05,886 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2010-08-31 13:53:06,126 adaptive_thread_pool.py] [Thread-3] WorkerThread: exiting
[DEBUG    2010-08-31 13:53:06,126 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2010-08-31 13:53:06,126 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2010-08-31 13:53:06,126 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2010-08-31 13:53:06,127 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2010-08-31 13:53:06,127 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2010-08-31 13:53:06,127 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2010-08-31 13:53:06,127 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[ERROR    2010-08-31 13:53:06,127 adaptive_thread_pool.py] Error in Thread-1: invalid literal for int() with base 10: 'Gewicht'
[DEBUG    2010-08-31 13:53:06,128 adaptive_thread_pool.py] Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/adaptive_thread_pool.py", line 150, in WorkOnItems
    status, instruction = item.PerformWork(self.__thread_pool)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 846, in _TransferItem
    self.content = self.request_manager.EncodeContent(self.rows)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 1267, in EncodeContent
    entity = loader.create_entity(values, key_name=key, parent=parent)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 2522, in create_entity
    properties[name] = converter(val)
ValueError: invalid literal for int() with base 10: 'Gewicht'

[DEBUG    2010-08-31 13:53:06,138 bulkloader.py] Waiting for progress_thread to terminate...
[DEBUG    2010-08-31 13:53:06,203 bulkloader.py] [Thread-11] ProgressTrackerThread: exiting
[DEBUG    2010-08-31 13:53:06,227 bulkloader.py] ... done.
[INFO     2010-08-31 13:53:06,227 bulkloader.py] 13 entites total, 0 previously transferred
[INFO     2010-08-31 13:53:06,228 bulkloader.py] 0 entities (724 bytes) transferred in 1.9 seconds
[INFO     2010-08-31 13:53:06,228 bulkloader.py] Some entities not successfully transferred
